GET http://localhost:3000/articles?take=5&skip=10 HTTP/1.1
### !!
GET http://localhost:3000/articles/6
### !!
POST http://localhost:3000/articles

Content-Type: application/json

{
    "titre": "Article Test",
    "contenu": "Ceci est un test",
    "image": "https://picsum.photos/500/300.jpg?",
    "createdAt": "2023-05-14T00:00:00.000",
    "updatedAt": "2023-05-14T00:00:00.000",
    "published": true,
    "userId" : 55
}
### !!!
PATCH http://localhost:3000/articles/6

Content-Type: application/json

{
  "title": "Article mis à jour",
  "contenu": "Nouveau contenu de l'article",
  "published" : true
}
### !!
DELETE http://localhost:3000/articles/6