GET http://localhost:3000/articles
### 
GET http://localhost:3000/articles/210
### 
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "Article Test d'ajout pour projet",
  "contenu": "Ceci est un test",
  "image": "https://picsum.photos/500/300.jpg?",
  "createdAt": "2023-05-14T00:00:00.000",
  "updatedAt": "2023-05-14T00:00:00.000",
  "published": true,
  "categories": [61, 62],
  "userId": 85
}

### !!
PATCH http://localhost:3000/articles/206

Content-Type: application/json

{
  "title": "Article Test Modif",
  "contenu": "Ceci est un test de modification de l'article 206",
  "image": "https://picsum.photos/500/300.jpg?",
  "createdAt": "2023-05-14T00:00:00.000Z",
  "updatedAt": "2023-05-14T00:00:00.000Z",
  "published": true,
  "categories": [61, 62],
  "userId": 85
}
### 
DELETE http://localhost:3000/articles/210