###
GET http://localhost:3000/categories?take=5&skip=0
### Get category by id
GET http://localhost:3000/categories/52


###
### Create new category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "nom": "New category added in db"
}

### Update category 
PATCH http://localhost:3000/categories/57
Content-Type: application/json

{
    "nom": "An updated category"
}

### Delete category
DELETE http://localhost:3000/categories/57
