###
GET http://localhost:3000/users?take=15&skip=0
###
GET http://localhost:3000/users/66

###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "nom" : "Youness",
    "email" : "youness@gmail.com",
    "password": "ensam",
    "role": "AUTHOR"
}
####
DELETE  http://localhost:3000/users/68
###
PATCH  http://localhost:3000/users/66
Content-Type: application/json

{
    "nom": "nouhayla",
    "email" : "nouhayla@gmail.com",
    "password": "123456",
    "role": "ADMIN"
}